#!/bin/bash

set -ex

pdfs=""
for x in burner-credentials_out*.svg; do
    out="${x%%.svg}.pdf"
    inkscape --export-pdf-version=1.5 --export-pdf=$out "$x"
    pdfs="$pdfs $out"
done
pdftk "$pdfs" cat output "$1"
